on:
  push:
    tags:
      - '*'  # этот шаблон означает запуск при любом теге
jobs:
  Job1:
    name: Job 1
    runs-on: ubuntu-latest
    steps:
      - name: sleep
        run: echo "shalalaalal"

